### ISSUE TITLE
[Feature Request] Support marker clustering

### ISSUE THREAD

**Issue by nachtien** [p-lr/MapCompose#3]
As seen with Google Maps here: https://developers.google.com/maps/documentation/javascript/marker-clustering

Thanks!

**Comment by peterLaurence** [comment]
Yes it should possible to have a library support for that, and it's already possible to have a user implementation (using the markers API).
A cluster can be seen as a special kind of marker. Depending on the scale and scroll, a controller can measure the distance between markers and decide which cluster to add/remove. It's not difficult to do (but not easy nonetheless).

I'll work on that when I have time for this.

**Comment by p-lr** [comment]
I went ahead and integrated the feature into the library. It turned out to be harder than I thought, as it required a revamp of the internals (just the markers feature).
The initial demo was more of a stress test (400 markers is quite a lot), so i moved it into the test app which was done for this purpose.
The demo app now has a "Marker clustering" demo. The issue with the cluster not revealing its markers at max scale is fixed. Also, by default, when a cluster is clicked, the map is zoomed just enough the reveal the content. This behavior can be disabled, or changed.

Since this is a brand new api, user code must use the `@OptIn(ExperimentalClusteringApi::class)`, to acknowledge the fact that these clustering apis might evolve.
Any feedback is welcome!
