### ISSUE TITLE
How do I update layers？

### ISSUE THREAD

**Issue by Huangkaiping** [p-lr/MapCompose#54]
with(state) {
        addLayer(tileStreamProvider)
 }
I want to constantly update the layer， But there was a crash： java.lang.OutOfMemoryError: Failed to allocate a 17572876 byte allocation with 8388608 free bytes and 15MB until OOM   
at  :
 val bitmapForLayer = layerIds.associateWith {
            Bitmap.createBitmap(tileSize, tileSize, bitmapConfig)
  }

**Comment by p-lr** [comment]
OutOfMemoryError (OOM) means you're using the memory too much. Most probably not due to the library.
There's a [stress test](https://github.com/p-lr/MapCompose/blob/master/testapp/src/main/java/ovh/plrapps/mapcompose/testapp/features/layerswitch/LayerSwitchViewModel.kt) of MapCompose which frequently updates layers.
