### ISSUE TITLE
Map padding for camera moves

### ISSUE THREAD

**Issue by Nohus** [p-lr/MapCompose#57]
I need a padding feature where I could set the map's padding for the purpose of camera moves. I have a partially obscured map (by my own UI), and want to scroll the map to various locations, and have them end up centered in the actually visible portion of the map, not the actual center as they do now. This video illustrates the concept in the Google Maps SDK: https://www.youtube.com/watch?v=HSCsdiqNjGo
Of course in Google Maps there is additional UI that is affected, in this case I only mean affecting `scrollTo` methods.

Would you accept a PR implementing this? In short this would add a new `setCameraPadding(...)` method to the API, which then the `scrollTo` family of methods would take into account to offset the scroll.

**Comment by p-lr** [comment]
Sounds like a good idea, I would happily accept a PR for that. My thoughts:
- What about just `setPadding(...)` for the api name, like the Google Maps SDK?
- The padding can be changed at runtime. Consequently, calling `setPadding(...)` should trigger a scroll update. Imperatively recalculating the scroll by calling `ZoomPanRotateState.setScroll(currentScrollX, currentScrollY)` triggers a scroll update (and since the scroll is a State, an UI update).

**Comment by Nohus** [comment]
- I thought `setPadding()` risks being confusing, as if it was setting the actual padding like `Modifier.padding()`. But I'm happy with either name.
- Good point!

**Comment by p-lr** [comment]
Alright then, pick the name you find most appropriate.

**Comment by p-lr** [comment]
Did you make progress on this?

**Comment by Nohus** [comment]
I didn't have time recently to finish this, but it's in progress, I'll try to have a PR this week.
