### ISSUE TITLE
Unable to add polygon lines in Mapstate

### ISSUE THREAD

**Issue by sriNaniTrst01** [p-lr/MapCompose#94]
Dear Team,

Am trying to integrate the polygon line between the existed markers but it's not working properly can you please help me on that

**Comment by p-lr** [comment]
In the demo app, there is the custom draw demo, which shows various geometries. In particular, there are lines drawn between specific positions. Relevant code is [here](https://github.com/p-lr/MapCompose/blob/master/demo/src/main/java/ovh/plrapps/mapcompose/demo/ui/screens/CustomDraw.kt). You'll find for example:

```kotlin
@Composable
fun Line(
    modifier: Modifier,
    mapState: MapState,
    color: Color,
    p1: Offset,
    p2: Offset
) {
    DefaultCanvas(
        modifier = modifier,
        mapState = mapState
    ) {
        drawLine(color, start = p1, end = p2, strokeWidth = 8f / mapState.scale)
    }
}
```

You can adapt this to use `drawLines` instead of `drawLine` to draw any kind of polygon.
